In [14]:
%config InlineBackend.figure_format = "retina"

from matplotlib import rcParams

rcParams["savefig.dpi"] = 100
rcParams["figure.dpi"] = 100
rcParams["font.size"] = 20

In [15]:
import numpy as np

In [30]:
def log_prob(x, mu, cov):
    diff = x - mu
    return -0.5 * np.dot(diff, np.linalg.solve(cov, diff))

In [38]:
ndim = 5
np.random.seed(42)
means = np.random.rand(ndim)

cov = 1 - np.random.rand(ndim**2).reshape((ndim, ndim))
print(cov)

[[0.84400548 0.94191639 0.13382385 0.39888499 0.29192742]
 [0.97941551 0.03009015 0.16755736 0.78766089 0.81817503]
 [0.81659549 0.69575776 0.47524357 0.56805498 0.70877086]
 [0.38814711 0.86050614 0.70785535 0.63363816 0.54393002]
 [0.21482404 0.80032622 0.48576556 0.40758543 0.95354959]]


In [39]:
cov = np.triu(cov)
print(cov)

[[0.84400548 0.94191639 0.13382385 0.39888499 0.29192742]
 [0.         0.03009015 0.16755736 0.78766089 0.81817503]
 [0.         0.         0.47524357 0.56805498 0.70877086]
 [0.         0.         0.         0.63363816 0.54393002]
 [0.         0.         0.         0.         0.95354959]]


In [40]:
cov += cov.T - np.diag(cov.diagonal())
print(cov)

[[0.84400548 0.94191639 0.13382385 0.39888499 0.29192742]
 [0.94191639 0.03009015 0.16755736 0.78766089 0.81817503]
 [0.13382385 0.16755736 0.47524357 0.56805498 0.70877086]
 [0.39888499 0.78766089 0.56805498 0.63363816 0.54393002]
 [0.29192742 0.81817503 0.70877086 0.54393002 0.95354959]]


In [41]:
nwalkers = 32
p0 = np.random.rand(nwalkers, ndim)

In [42]:
import emcee

sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, args=[means, cov])

In [43]:
log_prob(p0[0], means, cov)

5.0260937196613416

In [44]:
state = sampler.run_mcmc(p0, 100)
sampler.reset()

In [45]:
sampler.run_mcmc(state, 10000)

/home/xia/.local/lib/python3.8/site-packages/emcee/moves/red_blue.py:99: RuntimeWarning: invalid value encountered in double_scalars
  lnpdiff = f + nlp - state.log_prob[j]


State([[ 4.82652528e+152 -6.11178207e+151  3.10227319e+153 -1.10685501e+153
  -3.02894455e+152]
 [ 1.11199580e+153 -1.40810948e+152  7.14740846e+153 -2.55011224e+153
  -6.97846468e+152]
 [ 4.42608595e+152 -5.60470963e+151  2.84488882e+153 -1.01502325e+153
  -2.77764399e+152]
 [-7.54076953e+152  9.54880319e+151 -4.84686722e+153  1.72930587e+153
   4.73230149e+152]
 [-6.70898412e+152  8.49552141e+151 -4.31223300e+153  1.53855460e+153
   4.21030446e+152]
 [-5.23694219e+152  6.63148902e+151 -3.36607071e+153  1.20097489e+153
   3.28650667e+152]
 [-3.72675665e+152  4.71915573e+151 -2.39539142e+153  8.54647809e+152
   2.33877139e+152]
 [-6.96235868e+152  8.81636714e+151 -4.47509076e+153  1.59666035e+153
   4.36931274e+152]
 [-5.75816512e+152  7.29150854e+151 -3.70108935e+153  1.32050565e+153
   3.61360645e+152]
 [-8.11005610e+152  1.02696852e+152 -5.21277900e+153  1.85985894e+153
   5.08956419e+152]
 [-5.14830782e+152  6.51925217e+151 -3.30910053e+153  1.18064859e+153
   3.23088309e+152]
 [ 5